### ISSUE TITLE
why its only blinking ???

### ISSUE THREAD

**Issue by aponfurious** [spacehuhn/esp8266_deauther#1023]
I changed the attacktimeout to 0. I flash it through arduino IDE software it flash successfully. After flash it only LED light is blinking nothing happen, i also try .bin file by export it from arduino IDE BUT the bin that i download from github is work fine. what is the solution?? 
OR it is possible to send me a deauther .bin file with attacktimeout=0.
if it possible then send it through gmail ..
mail:aponfurious@gmail.com

**Comment by sro2** [comment]
Board number send me

On Jan 7, 2019 5:01 PM, "aponfurious" <notifications@github.com> wrote:

I changed the attacktimeout to 0. I flash it through arduino IDE software
it flash successfully. After flash it only LED light is blinking nothing
happen, i also try .bin file by export it from arduino IDE BUT the bin that
i download from github is work fine. what is the solution??
OR it is possible to send me a deauther .bin file with attacktimeout=0.
if it possible then send it through gmail ..
mail:aponfurious@gmail.com

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/spacehuhn/esp8266_deauther/issues/1023>, or mute the
thread

**Comment by aponfurious** [comment]
board no: esp8266
please send me the bin file please..

**Comment by aponfurious** [comment]
is no one is here to help me????
