### ISSUE TITLE
 A_config.h:7:24: error: SH1106Wire.h: No such file or directory

### ISSUE THREAD

**Issue by yousifja** [spacehuhn/esp8266_deauther#1042]
Arduino: 1.8.7 (Windows 7), Board: "NodeMCU 0.9 (ESP-12 Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

In file included from sketch\Settings.h:11:0,

                 from C:\Users\ttt\Desktop\esp8266_deauther-master\esp8266_deauther-master\esp8266_deauther\esp8266_deauther.ino:27:

A_config.h:7:24: error: SH1106Wire.h: No such file or directory

 #include "SH1106Wire.h"

                        ^

compilation terminated.

exit status 1
SH1106Wire.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by itsjustme** [comment]
make sure you selected you're Board under "ESP8266 Deauther Modules"

**Comment by sarptekbas** [comment]
> make sure you selected you're Board under "ESP8266 Deauther Modules"

thanks

**Comment by tobozo** [comment]
Closing this issue as inactive, feel free to reopen if necessary.

**Comment by sabidkaral** [comment]
I have the some problem... i already tried out all kinds of esp8266 boards but still have the error

**Comment by edeavila** [comment]
> I have the some problem... i already tried out all kinds of esp8266 boards but still have the error

same

**Comment by Fearce1** [comment]
The FILE IS MISSING. I've had this problem ALONG WITH MANY others after attempting to "UPDATE" a Dstike OLED MINI V2. The web-interface used to work FINE then I tried to upgrade from the original version it was shipped with (thinking UPGRADE MEANS BETTER) and get a rabbithole of MISSING FILES and LOST FUNCTIONALITY. Seems very intentional for all of these things to suddenly not be in the DOWNLOADABLE SOURCE(S) of each of these versions. The file is NOT INCLUDED in the SOURCE .zip You can DL version 2 that calls the file from the settings.h file. Below shows the .h files and "SH1106Wire.h" IS NOT IN THERE.
![image](https://github.com/SpacehuhnTech/esp8266_deauther/assets/60891352/9ce8b098-4908-4f4e-a1d6-d56a53f1529c)
![image](https://github.com/SpacehuhnTech/esp8266_deauther/assets/60891352/f650bb41-1f0f-4c67-b6af-8f8855dea0a9)

Seems like it was LEFT OUT of the downloadable files... WHY?

**Comment by Fearce1** [comment]
The reason I even attempted a update is so the WEB interface would load the SSID's and NAMES. Every WORKING version throws this error:
ERROR: saving file. Try 'format' and restart - /scan.json
# save names
ERROR: saving file. Try 'format' and restart - /names.json
# format -names.json
Formatting SPIFFS...OK
# save scan
ERROR: saving file. Try 'format' and restart - /scan.json
# save names
ERROR: saving file. Try 'format' and restart - /names.json
