### ISSUE TITLE
Randomise the attacks

### ISSUE THREAD

**Issue by tytower** [spacehuhn/esp8266_deauther#1153]
So it would be better if the deauther attack were not permanently on. 
It would be much better to switch it on and off each say, 20 seconds and let the wifi reconnect and work for a while and then swith deauthor on for a while .

I don't see that this facility is available here now but I wonder if there is an experienced coder that has worked on this project that can tell me where the randomising code would go . 

I'm quite able to write the code but there are many programs in there and not being familiar with them I just need a pointer to where it might be best placed. That would save me a lot of catchup time if someone can be bothered .

I can probably tie this in with the randomising request in issue #1125 I think.

Clearly there is a random function there already
 "RANDOM
enable random <interval>
Enables SSID random mode with given interval in seconds.
disable random Disables SSID random mode.

**Comment by 13r1ckz** [comment]
Thank you for the interest in this code.

Tis option you talked about will not be included in to the code.
Tis will not happen due to this being a development/test tool. So this tool is not made to be annoying it is meant to check your network or try other deauther related test.
As the included license says you are allowed to modify the code the way you see fit for your use. This will not be our responsibility, or our task to make.

We will close this issue now because this will have no future.
