### ISSUE TITLE
CRC doesn't match, file is corrupted

### ISSUE THREAD

**Issue by grcasanova** [spacehuhn/esp8266_deauther#1155]
When trying to install _arduino-esp-deauther tool_, an error message is shown.
`CRC doesn't match, file is corrupted`

- Older IDE version, fixed

**Comment by tobozo** [comment]
This happens because no .sig file is present along with the deauther json file, apparently the boards manager only complains once when this file returns a 404 error.

I'm not sure if this is by design, but it could sound like a security issue in Arduino IDE checking only once the crypto chain, but it's fortunate this issue exists because there is no .sig file indeed, and a correct behaviour would be to ignore the deauther json file.

Now that Arduino IDE 1.8.10 is out, we'll soon see if the 'issue' is fixed. 
I don't know how to produce this .sig file though (GPG + some dev profile ?). Any insight on this is welcome. (poke @spacehuhn )
