### ISSUE TITLE
Deauther OLED V6 - "resistor beside IPEX connector removing"

### ISSUE THREAD

**Issue by MrCook1es** [spacehuhn/esp8266_deauther#1251]
Good morning, I would like additional information about "resistor beside IPEX connector removing".
1) Was this resistance also present on the OLED V5 model?
2) The image below indicates the possibility of removing the resistance in order to obtain the "best effect" from the antenna. Why was the resistance included in the project? Is it because of the national regulations on the power Tx (mW)?
![immagine](https://user-images.githubusercontent.com/38523505/83623494-b09ad700-a591-11ea-9bd1-fe4dd7a817a5.png)

**Comment by tobozo** [comment]
for a "best effect", nothing beats an amplifier

![image](https://user-images.githubusercontent.com/1893754/83628892-85b48100-a599-11ea-9762-bbd861781165.png)

edit: [source](https://rf-market.fr/qo-100-satellite/434-amplificateur-24-ghz-qo-100-20w-pe1cmo.html)

**Comment by spacehuhn** [comment]
I think this is simply due to the use of the ESP-07 module. A common ESP8266 module that comes with the antenna connector but also a ceramic antenna. And if you remove the resistor, it will only be connected to IPX connector. Which means you **have** to have an external antenna connected (otherwise you can damange the device) but you also don't lose any energy to the less powerful ceramic antenna.
![grafik](https://user-images.githubusercontent.com/3826044/84874022-4f403100-b084-11ea-8181-d98258ad618c.png)

**Comment by MrCook1es** [comment]
@spacehuhn thanks for the precise information.
I will be careful never to turn on my DSTIKE oled V5, without an external antenna connected.

there are different types of IPEX connectors, can you confirm that the one on your DSTIKE is an IPEX (MHF-4) type?
![immagine](https://user-images.githubusercontent.com/38523505/84890341-90434000-b09a-11ea-8e6c-e22d16257a21.png)

**Comment by spacehuhn** [comment]
It's this one, don't ask me about the mess and confusion over the different connector standard and names
https://en.wikipedia.org/wiki/Hirose_U.FL
