### ISSUE TITLE
what is the requested memory for the script  ??

### ISSUE THREAD

**Issue by minanagehsalalma** [spacehuhn/esp8266_deauther#129]
@spacehuhn

**Comment by spacehuhn** [comment]
Installation

The only thing you will need is a computer and an ESP8266.

I recommend you to buy a USB breakout/developer board, because they have 4Mb flash and are very simple to use. It doesn’t matter which board you use, as long as it has an ESP8266 on it.

You have 2 choices here. Uploading the bin files is easier but not as good for debugging, so keep that in mind in case you want to open an new issue.

**Comment by minanagehsalalma** [comment]
@spacehuhn ok
