### ISSUE TITLE
ERROR: ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by zedeme** [spacehuhn/esp8266_deauther#1366]
Explanation in English (translator): everything is great for me, the problem is when I enter 192.168.4.1 or deauth.me, it rejects the connection or says that it is interrupted, any contribution helps, Thanks you.

Explicación en español: todo me anda fenomenal, el problema es cuando entro a 192.168.4.1 o deauth.me, me rechaza la conexión o bien dice que se interrumpe, cualquier aporte ayuda, Gracias.

ping: [https://gyazo.com/ed337691d4d4a3e3d908648770cdc552](url)

ipconfig: [https://gyazo.com/970924030abb0b993157c4b82e1fa0ab](url)

**Comment by 5ch4um1** [comment]
Not sure if it helps in your case, but i had all sorts of weird connection errors (lots of them, of different nature), seems because i was in a very "radio quiet" place and there were no APs for the initial scan, so it kept scanning. Make an AP with my phone so it has something to scan, wait until the blue led turns off, and then i'm able to connect just fine. The serial monitor is a great place to find errors, if this was not the issue, you might find hints about your error there.

Y de verdad, intenta escribir en ingles, lo del traductor se entiende perfectamente, pero no todo el mundo habla español... ;)
De todas formas, por si estas en un sitio sin redes, haz p.e. una "zona wi-fi" con el movil y espera un momentito hasta que la led azul se apaga, y mira si ya te funciona. :)
