### ISSUE TITLE
preselect WiFi APs

### ISSUE THREAD

**Issue by Hammad1029** [spacehuhn/esp8266_deauther#54]
Can you add a feature to preselect WiFi ssids? like if I know the ssid of the WiFi of the place I'm going to, I'll select it before leaving and it'll start spamming deauth packets to that WiFi. Whether by waiting to detect the specific ssid or spamming deauth packets dedicated to that WiFi before getting in its vicinity. Is it even possible? if yes can you add it please

**Comment by joneroy** [comment]
it's possible

**Comment by Skulkx** [comment]
I have a Feature Request which is actually quite similar to this one.
I would love to have the option to automatically start an Attack on PowerOn.

So that i can set up, lets say, a Beacon-Jammer-Attack, at home. Then, at the site, i'll power the ESP8266 via Battery and the defined Attack would launch

Thank you very much for your precious time :-)
