### ISSUE TITLE
APScan crash

### ISSUE THREAD

**Issue by rfvcdewsxzaq** [spacehuhn/esp8266_deauther#609]
Exception (29):
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffd80 end: 3fffffb0 offset: 01a0

>>>stack>>>
3fffff20:  40282420 00000000 0000000d 4020d588  
3fffff30:  402315fc 3ffef91c 3fff5c98 40231616  
3fffff40:  00000000 402313ff 3ffef934 3ffe9f30  
3fffff50:  0ba4864e 3ffef934 3ffe9f30 0ba4864e  
3fffff60:  40231890 3ffec338 3fff640c 60000600  
3fffff70:  4021bdd5 3ffe9f30 3ffea2cc 4021bdd5  
3fffff80:  4021be1a 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffe9f40 3fffdc20 3fff429c 40210c3f  
3fffffa0:  40000f49 3fffdab0 3fffdab0 40000f49  
<<<stack<<<

**Comment by tobozo** [comment]
Sounds like #587 I'll close this ticket since it's a duplicate.

If you're not using the OLED build, feel free to reopen it and provide as much details as possible.

As a temporary workaround you can try the [serverless](https://github.com/spacehuhn/esp8266_deauther/tree/serverless) branch. This disables the web server and removes the crash situation when in busy areas.

Otherwise just add a comment to #587 so you'll get notified when this is fixed.
