### ISSUE TITLE
pwned network  is  not showing up

### ISSUE THREAD

**Issue by noahnow2004** [spacehuhn/esp8266_deauther#672]
I was able to do this a month ago when I got this thing, but then a week ago when put a check on the setting, 'Hide SSID' I have never been able to find the network it creates, 'pwned'. I deleted the program and then put it back on but it still does not work. PLEASE HELP. I NEED IT FAST

**Comment by PxLtommy** [comment]
When in network settings on another device, you need to click 'other', and enter its name, security etc

**Comment by MrAppAndCrap** [comment]
Connect the board to your pc via usb. Flash the .bin files (https://github.com/spacehuhn/esp8266_deauther#installation) After you finish flashing unplug the device, plug it into a phone charger socket or a 3.0+ usb port on your computer. You should see the wifi network now. The reason for plugging it into a good phone charger is because it might not be pulling enough power from usb ports on pc's.

**Comment by Johnsjs232** [comment]
I am having the same problem I flashed my esp8266 with nodemcu firmware programmer it said it was successful but when I went to use it it would not give off a wifi signal. I have no idea what to do to fix it

**Comment by Johnsjs232** [comment]
I tried plugging it into the wall too

**Comment by tobozo** [comment]
see if it is fixed in the next version, reopen if necessary

closing this

**Comment by fankaisong** [comment]
I have the same issue. I just bought it today and followed all instruction. The pwned just not showing after it.  I tried "Blinking" example on Arduino and it worked.  So, the other thing was that when I runed EEPROM earase from Arduino, the pwned wifi showed up

**Comment by rogaha** [comment]
same issue here
