### ISSUE TITLE
Automatic restart when attack starts in the Oled interface

### ISSUE THREAD

**Issue by vuong244** [spacehuhn/esp8266_deauther#743]
When I attacked all the stations found in the Oled interface, my board was restarted. I tried with another board, the same result

**Comment by tobozo** [comment]
ping #741.

How many stations did you select ?
Did you select the stations using the buttons, the web GUI, or from the terminal ?

Can you test the following situations:
- attack without selecting any stations
- attack when only one station is selected (and increment the number of selected stations)

Also can you specify the phone/browser you're using along with the version of the deauther.

**Comment by spacehuhn** [comment]
Fixed with commit https://github.com/spacehuhn/esp8266_deauther/commit/e494d95c15e689edd8eff140015c2fd53191d3fd
So just download/clone the repository, compile and upload and you should be good. If you need a .bin file let me know but I strongly recomment using Arduino as explained here: https://github.com/spacehuhn/esp8266_deauther/commit/e494d95c15e689edd8eff140015c2fd53191d3fd 
Because of the better debugging possibilities.

**Comment by vuong244** [comment]
Thank you. it was working
