### ISSUE TITLE
Format

### ISSUE THREAD

**Issue by AnthonyFuller** [spacehuhn/esp8266_deauther#868]
How do I format it?

**Comment by AnthonyFuller** [comment]
Externally? Since I can't access it.

**Comment by AnthonyFuller** [comment]
Reopen it.

**Comment by digmorepaka** [comment]
You use the serial port. And if you mean externally like its stolen and you don't have access to it, simple answer: You don't.

**Comment by AnthonyFuller** [comment]
It isn't stolen. It's just that I messed up flashing it.

**Comment by tobozo** [comment]
This command can't be executed from the WebUI if that's what you're asking.
If you can connect via serial, you just send the "format" command and it'll format the SPIFFS.

Otherwise every time you flash the deauther sketch, on next reboot (and only once) the ESP8266 will format the SPIFFS automatically.

**Comment by AnthonyFuller** [comment]
nvm about to get putty up and do it through serial

**Comment by AnthonyFuller** [comment]
I get this 
![ghudnelmo](https://user-images.githubusercontent.com/24512050/40248888-3e44a650-5ac9-11e8-973f-85a63bd7c1be.png)

**Comment by digmorepaka** [comment]
use esptool to erase it and reflash it
